### ISSUE TITLE
Void Quill throwing NREs

### ISSUE THREAD

**Issue by Coffe-e** [Zenithrium/vanillaVoid#12]
**Describe the bug**
upon picking up the Void equivalent of Hopoo Feather (I forget it's name.), NREs start to trigger, and inputting space mid-air seems to not do anything half the time.

**To Reproduce**
1. Start a Run
2. Obtain Void Quill
3. Attempt to Airdash

**Expected behavior**
For Void quill to not have it's input eaten, or throw NREs

**Screenshots**

**Additional Mods**
I don't think any of my mods would cause this error, since it worked fine when I obtained it before the most recent update.

**Additional context**
I was in Simulacrum, playing Engineer.

**Log File**
Apologies but I went for a long time during the run, so the text file size was too big uncompressed.
[LogOutput.zip](https://github.com/Zenithrium/vanillaVoid/files/10313834/LogOutput.zip)

**Comment by Zenithrium** [comment]
Oh, just noticed this - Hopefully 1.4.1 fixed this bug but I'll give it a little time to make sure

**Comment by Zenithrium** [comment]
going to close this since there hasn't been any mention of quill NREs since 1.4.1 or 1.4.2. Hopefully it's fine!
