### ISSUE TITLE
Extraterrestrial Exhaust bugged activation with engineer turret

### ISSUE THREAD

**Issue by Meyslaq** [Zenithrium/vanillaVoid#19]
**Describe the bug**
Extraterrestrial exhaust activates when engineer selects the turret as opposed to when the turret is placed when one charge is on cooldown.

**To Reproduce**
Place one turret down so that you have 1 turret available to place but 1 on cooldown. Select turret placement but don't place the turret, right click to cancel placement, repeat. Using secondary or utility skill will fix it most of the time, but placing another turret down will start the bug again.

**Expected behavior**
Missiles from EE only activate on turret placement, selecting and deselecting turret does not do anything.

**Video**
[VideoDemonstration.zip](https://github.com/Zenithrium/vanillaVoid/files/12044168/VideoDemonstration.zip)

**Additional Mods**
Bug tested using vanilla void and debug toolkit

**Log File**
BepInEx log
[LogOutput.log](https://github.com/Zenithrium/vanillaVoid/files/12043952/LogOutput.log)

**Comment by Zenithrium** [comment]
Should be an easy fix - I'll try get around to it tomorrow

**Comment by Zenithrium** [comment]
Fixed in 1.5.7. Thank you for the report !
