### ISSUE TITLE
Orrery Rework Idea

### ISSUE THREAD

**Issue by PIEisFANTASTIC** [Zenithrium/vanillaVoid#2]
thejanjan and I were looking at the code and specifics for the orrery item and decided it was a bit underwhelming, especially when compared to the item it corrupts, laser scope. Below is a pretty in depth idea of a rework for the item.

Crit Dipping: rework crit dipping; each dip is if a crit procs, roll another crit proc for [1/2] of the last proc's % chance 
previousCritProc * (0.5 * 0.95^(orrerystacks-1))
Ex. 90% crit procs with 2 orrery in items, roll for a second crit with a 45% proc chance. If that 45% procs roll a 22.5% proc chance to crit again.
This allows for the dipping mechanic to take place with less than 100%+ crit chance.

Crit Damage: Change damage calc for orrery to have slightly more aggressive dmg scaling than scope, with higher than 100% crit 
Formula: damageInfo.damage *= (attackerBody.critMultiplier + max((baseLevel - 1), 0) * max(baseLevel, 1)
This change is conceived by the fact the the current orrery dipping is just the same linear damage scaling as laser scope. This allows for a reason to consider carrying a bunch of crit goggles with orrery.

35% more effectiveness on Crit Glasses and Lost Seer's (no orrery stacking)
This is similar to the 15% increased effectiveness now, just without further stacking with more orrerys. (janjan and I also couldn't find the code where lost seer's gets the increased effectiveness, so perhaps that's worth looking into)

Item Description:
Critical strikes can dip 1 (+1 per stack) time(s), each dip is 50% (-5% per stack) the proc chance of the last chance roll. Critical damage scales beyond 100% critical chance.
35% increased effectiveness on lens-based items.

**Comment by Zenithrium** [comment]
That's probably better, yea. I'll rework it at some point, trying to get three items finished and one of them is being a pain. The lost seer's stacking effect is in Main.cs, because I used an IL hook for it

**Comment by Zenithrium** [comment]
reworked to roughly this idea, didn't include the crit damage increase in the description though for three reasons - i made it a super minor increase, it doesnt stack per orrery, and also it might make it seem way better than laser scope
