### ISSUE TITLE
Clockwork Mechanism variations that increase Director Credits do not work in Simulacrum

### ISSUE THREAD

**Issue by WolfoIsBestWolf** [Zenithrium/vanillaVoid#23]
RoR2.InfiniteTowerRun.OnPrePopulateSceneServer does a big "credits = 600" after the normal PrePopulate that you hook into so you gotta hook into this one too and do the multiplier/additions again.

On.RoR2.InfiniteTowerRun.OnPrePopulateSceneServer += (orig, self, sceneDirector) =>
            {
                orig(self, sceneDirector);
//Your code here
            };

**Comment by Zenithrium** [comment]
oh okay, thanks for pointing that out! i'll update tonight hopefully

**Comment by Zenithrium** [comment]
should be fixed in 1.5.10!
