### ISSUE TITLE
Void Feather softlocks your movement if used when you have RoR2Content.Buffs.LunarSecondaryRoot

### ISSUE THREAD

**Issue by WolfoIsBestWolf** [Zenithrium/vanillaVoid#25]
You could probably just check if body has 0 movement speed instead of 3 checks for buffs since the buffs just set your movement speed to 0. Nullifed/Rooted work fine because of the check you do have tho.

https://github.com/Zenithrium/vanillaVoid/assets/124494077/e2f21c25-c33d-41a5-8d94-27813aa46507

**Comment by Zenithrium** [comment]
Should be fixed in 1.5.11!
