### ISSUE TITLE
Void Elixir regeneration code runs twice.

### ISSUE THREAD

**Issue by WolfoIsBestWolf** [Zenithrium/vanillaVoid#29]
2 regenerate per stage with a value of 1 (or well default).

This is probably because you have RefreshVials() in both EnhancementVials.cs and EmptyVials.cs

**Comment by Zenithrium** [comment]
will be fixed in 1.6! thank you for the report; sorry for taking so long.

**Comment by Zenithrium** [comment]
should be fixed in 1.5.14 actually!
