### ISSUE TITLE
Mithrix removes you from reality when taking your quasi-temporal quills

### ISSUE THREAD

**Issue by Mohl97** [Zenithrium/vanillaVoid#30]
**Describe the bug**
When Mithrix goes into his last phase and starts taking items, you get forcibly despawned when he takes the void quill. This doesn't end the game, oddly enough, and you can still respawn with debugtoolkit.

**To Reproduce**
1. acquire Quasi-temporal Quill
2. Fight mithrix
3. reach last phase of mithrix
4. :ooooaaauuugghhhDust:

**Expected behavior**
He should simply take the quill, and not your soul/body with it.

**Screenshots**
[This is a short clip I took and posted on discord.](https://cdn.discordapp.com/attachments/1197084229176147978/1245543076970233916/drivelessness.mp4?ex=665921e2&is=6657d062&hm=85935e2a3d39456eb854a90453b3c9d22fa1e0f7ff29c7db3f934cce8e63f3de&)

**Additional Mods**
there are a lot of mods in my pack, of which some I don't think are 100% functional, but I was told to report this here so I will. I don't have anything directly messing with mithrix's mechanics, however.

**Additional context**
none that I can think of.

**Log File**
unfortunately, the log file is gone as my game only keeps one per boot and I restarted the game shortly after, like a dumbass. The clip does have me pulling up the console for a second or so, but it doesn't look like there's anything relevant there, just void creatures from the escape sequence failing to spawn.

**Comment by Zenithrium** [comment]
oopsies! fixed in 1.5.15. thanks for the report!
