### ISSUE TITLE
Clockwork Mechanism spawns items in the Bazaar even though it's disabled in config

### ISSUE THREAD

**Issue by The-Haxor** [Zenithrium/vanillaVoid#31]
**Description**
Entering Bazaar Between Time with a Clockwork Mechanism spawns items. When entering the stage right after leaving the Bazaar it spawns items again. "Function in Bazaar" is disabled in config.

**To Reproduce**
1. Get a Clockwork Mechanism
2. Go to Bazaar Between Time
3. Leave and go to the next stage

It should spawn items when you get to the Bazaar and again once you get to the next stage even if the function is disabled in the config file.

**Expected behavior**
It shouldn't spawn items when you enter the Bazaar.

**Screenshots**
![Risk of Rain 2 Screenshot 2024 06 01 - 21 30 33 62](https://github.com/Zenithrium/vanillaVoid/assets/171461960/ed2711e3-ea55-4d2c-9e4f-1bcfc06b7255)
![Risk of Rain 2 Screenshot 2024 06 01 - 21 30 50 98](https://github.com/Zenithrium/vanillaVoid/assets/171461960/e86a9c1c-c4f0-427f-82fc-08d9a17f6128)

**Additional Mods**
![1](https://github.com/Zenithrium/vanillaVoid/assets/171461960/65230b71-94e3-4241-9c4e-bf58d838cedd)
![2](https://github.com/Zenithrium/vanillaVoid/assets/171461960/842a2062-2778-43e1-9e97-0d89e069fa1f)
![3](https://github.com/Zenithrium/vanillaVoid/assets/171461960/5fd6408f-0298-4698-a89e-edc293cdb548)
![4](https://github.com/Zenithrium/vanillaVoid/assets/171461960/e124359e-ff85-4de8-a346-76101cbf9e0c)

**Suggestion**
It'd be nice if there was config to make it only spawn items in stages that increase the stage counter. I didn't realize that it was intended for it to spawn stuff in Void Fields, A Moment Fractured, etc. :/

**Comment by The-Haxor** [comment]
Oh, it's also doing it when the variant is set to 1.
![Risk of Rain 2 Screenshot 2024 06 07 - 01 05 36 70](https://github.com/Zenithrium/vanillaVoid/assets/171461960/da423cf8-bb9d-498c-938d-b309d5fb95ef)
![Risk of Rain 2 Screenshot 2024 06 07 - 01 05 44 43](https://github.com/Zenithrium/vanillaVoid/assets/171461960/722bf49a-7cff-4a87-9a3c-bf306879eb09)

**Comment by Zenithrium** [comment]
should be fixed in 1.5.15 - thank you for the report !
