### ISSUE TITLE
Extraterrestrial Exhaust Engineer Spam

### ISSUE THREAD

**Issue by Justinfab** [Zenithrium/vanillaVoid#32]
When locking onto an enemy with Thermal Harpoons it counts every lock on as an ability use and the amount of void rockets fired is based on the current total cooldown of Harpoons available to fire, allowing you to fire endless rockets.

Upon locking on with 4 Harpoons you can just cancel the lock by pressing M2 and repeat this endlessly.

It should probably fire the rockets after the Harpoons have fired rather than for each lock on, allowing the cooldown to happen to prevent spam.

https://github.com/Zenithrium/vanillaVoid/assets/133853000/5717a7d4-36e6-4c94-b52d-915f5a61a17e

**Comment by Zenithrium** [comment]
ah oopsies! will fix this asap

**Comment by Zenithrium** [comment]
may or many not have completely forgot. Fixed in 1.5.16!
