### ISSUE TITLE
Clockwork Mechanism Variant 0 only drops Tier 1 Items

### ISSUE THREAD

**Issue by Saf3Haven** [Zenithrium/vanillaVoid#33]
**Describe the bug**
Clockwork Mechanism Variant 0 always drops Tier 1 items even if you skew the weights of the items towards Tier 2 and 3 in the config. This is happening when the items are dropped around you, which is the current default option.

My weights in this example (Tier 1, Tier 2, Tier 3) were .01, .01, .98.

**To Reproduce**
1. Start a stage and get some Clockwork Mechanisms
2. Go through a few stages to have the items spawn
3. All items dropped will be tier 1 regardless of weight

**Expected behavior**
I would expect the item weight to make it so i could control which tiers of items would usually drop from it. I also would expect that the item wouldnt only drop Tier 1s.

**Additional Mods**
Only other mods that were used are the various R2API mods and BepInExPack.

**Additional context**
My specific run that the log file is attached with is with command on. But i have observed this even without command on. I remember noticing this happening before SotS but i originally thought it was just a nerf. In addition i didnt test if it was also happening when items are directly put into your inventory instead of dropped around you.

**Log File**
I will attach the log in a few minutes, was writing this on my phone.

**Comment by Saf3Haven** [comment]
[LogOutput.log](https://github.com/user-attachments/files/16897889/LogOutput.log)

Log from the above-mentioned run is attached.

**Comment by Zenithrium** [comment]
whatt not again

**Comment by Saf3Haven** [comment]
no problem, just thought i should bring it up

**Comment by Zenithrium** [comment]
should be fixed!
