### ISSUE TITLE
Bubble Effects (Warbanner, Celestine Elite) spam "Teambuff" in console while active.

### ISSUE THREAD

**Issue by Coffe-e** [Zenithrium/vanillaVoid#34]
**Describe the bug**
Its not really that different from the title, so refer to there. Happens once every second per existing bubble effect, and can get pretty out of hand with mods. This also affects modded bubble effects like motivator elites from sandswept.

**To Reproduce**
1. Spawn an Enemy with a bubble effect (such as a celestine elite), or activate the teleporter with a warbanner in your inventory.
2. View the console while ingame.

**Expected behavior**
I imagine this isn't meant to happen.

**Screenshots**

**Additional Mods**
I did test it with just Vanilla Void and its dependencies, and it does seem to only be vanillavoid. (With debug toolkit to guarantee that I could set up the bug immediately)

**Additional context**
It hasnt been that big of an issue, but I imagine having potentially 10s of bubble effects all generating that in the log once per second would get kinda performance heavy.

**Log File**
[LogOutput.log](https://github.com/user-attachments/files/17107212/LogOutput.log)

**Comment by WolfoIsBestWolf** [comment]
this is like pretty bad, would be good to push an update with it fixed

**Comment by Zenithrium** [comment]
should be fixed, sorry about the huge delay !
