### ISSUE TITLE
Exhaust and Hungering Gaze interaction bugged.

### ISSUE THREAD

**Issue by CANADIANPIG** [Zenithrium/vanillaVoid#4]
Currently the Exhaust item (firework replacement) when used with Visions of Hersey (Hungering Gaze) causes the game to fire 3 missiles for every gaze projectile (3 projectiles for the 6 second CD). As written it should _only_ fire 3 total but instead is firing 3 for every projectile of hungering gaze you have, resulting in 36 projectiles firing with only one stack of visions of heresy. 
While the OP nature of this interaction is welcome, it seems to be insanely broken and an unintended interaction with the ability. Sadly I do not have a video due to lacking recording software, but can provide one if needed.

**Comment by prodzpod** [comment]
it says based on cooldown. are you using an old version?

**Comment by CANADIANPIG** [comment]
To clarify, it _is_ based on the current cool down of 6 seconds since the cooldown resets to max as you are firing hungering gaze. The issue is that the exhaust was balanced around typical cooldown abilities, such as Loader's Punch or Engie Turrets, not Hunger Gaze as they just fire of hundreds of missiles a second. I would assume this was intentional if it was hard to achieve, but it only requires two fairly easy items and appears to be a balanced issue/oversight. 
Was there a fix in a more recent version of the mod that corrects the Exhaust/Hungering Gaze interaction I have described?

**Comment by Zenithrium** [comment]
yea i need to make an exception for hungering gaze, didn't even consider this

**Comment by Zenithrium** [comment]
this should be fixed in .13, thanks for the report !
