### ISSUE TITLE
Some characters bugged (including modded)

### ISSUE THREAD

**Issue by Kaizuto** [Zenithrium/vanillaVoid#5]
Basically any character that has "click as fast as you can" fire rate like bandit m1, enforcer R, will be clicked more than 5 times even if u clicked once. Idk how this happened, there's not even an item from this mod acquired yet, even when starting a run this bug happens. Not sure if its the mod or the API tho. The console says a bunch of things i dont understand.

Also characters that attacks with left and right hand/swing like loader, acrid, paladin, it will only use the first hand/swing, eg. loader will only punch with right hand, acrid with left and paladin will only swing right

**Comment by prodzpod** [comment]
cannot repro. u sure its this mod that's causing it?

**Comment by Kaizuto** [comment]
Yes, I removed this mod and it works fine again

**Comment by CANADIANPIG** [comment]
Can you provide your full mod list?

**Comment by KamilTaruc** [comment]
Theres like 140+ mods and I keep on adding/removing them, do I just copy from the mods.yml from the profile folder or do I need to list manually?

**Comment by Kaizuto** [comment]
Theres like 140+ mods and I keep on adding/removing them, do I just copy from the mods.yml from the profile folder or do I need to list manually?

**Comment by CANADIANPIG** [comment]
If you have 140+ mods that is part of your issue most likely; that is a lot of mods. It most certainly is a conflict with one of them. I wouldn't know where to start with a mod list that long.

**Comment by Kaizuto** [comment]
Thought so but last time I used this mod (with my modlist) theres a big red text on the console for this mod and tinker's satchel (and probably some other item mod but not as much as these 2), uninstalled this mod and everything works again

**Comment by CANADIANPIG** [comment]
So on my shorter mod list of 20 items, I have no issue. I would advise that you start to determine what mod or mods are conflicting with VanillaVoid to create this issue as it is not an issue on a "clean" installation. The developer likely cannot isolate what can be done to correct this conflict, if anything, without knowing what other mod is causing this issue. 
The Red Text in console is not as important as it seems as plenty of mods throw errors that have no impact on gameplay.

**Comment by ujkpgs** [comment]
Hi, I have had the same issue for the past months and just now found out what mods were causing the issue. I started the game with just VanillaVoid (and VoidItemsAPI), Wisp_WarframeSurvivorMod and its dependencies, and I had this issue. Thought it would be helpful to let you know

**Comment by Zenithrium** [comment]
I think it's probably wisp mod - from when i've been working on SS2 it seems to commonly break stuff and cause issues. I'll definitely try look into it though and see if vv is reponsible
