### ISSUE TITLE
Minor stutter when first picking up or converting an item

### ISSUE THREAD

**Issue by cesmaster644** [Zenithrium/vanillaVoid#8]
It seems very similar to an issue with Starstorm 2's current version of Coffee Bag - like receiving any of this mod's void items causes a brief script lag or something. Obviously not as detrimental, since enemies can't receive void items and mass-lag the game, but still noticeable enough. 
Issue noticed on Supercritical Coolant, Executioner's Burden, and Clockwork Mechanism (variant 2); presumed on other items as well.

**Comment by Zenithrium** [comment]
hm. I haven't noticed it and I don't think it should be happening - AFAIK this is caused because the first pickup adds the item's hooks to the given functions, but i'm pretty sure i was lazy and just added them immediately on startup. i'll look into it lol

**Comment by Zenithrium** [comment]
Bit late to the party here, but the issue was relying on voiditemapi, as item transformations added by it caused significantly greater lag than conversions added in a more traditional way. Regardless, this is finally fixed!
