### ISSUE TITLE
Void Fiend acting weird

### ISSUE THREAD

**Issue by plwya** [Zenithrium/vanillaVoid#9]
Void Fiend with this mod enabled can use M1 and M2 while sprinting even in corrupted form.
UoCQvwB8IJ is my modlist code for R2ModManager. I have 67 mods but most of them like 20+ are for skins.

**Comment by plwya** [comment]
and somehow mercenary cant use default alternative again if he hit an enemy, as normal you can use it up to 3 times if you hit an enemy each dash.

**Comment by Zenithrium** [comment]
tested the void fiend bug and merc bug and can't reproduce either - if it is related to my mod, it's a weird cross-mod incompatibility, and for that i'd need a log file

**Comment by plwya** [comment]
captain can run while chargin his M1, loader attacks with only right hand, railgunner uses 2 stacks of her utility at once.
